# Generated by Django 5.1.4 on 2025-08-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basearticle',
            name='description',
            field=models.TextField(),
        ),
    ]
