name: Ping my website

on:
  schedule:
  # runs every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  ping_url:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: |
          curl -s -o /dev/null -w "%{http_code}" ${{ secrets.PING_URL }}
